name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code (this runs on the GitHub runner, not the server)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Connect to the server via SSH and deploy
      - name: Deploy application on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/topline-news
            git fetch origin main
            git reset --hard origin/main
            docker compose -f docker-compose.prod.yml --project-name topline-news-prod down || true
            COMPOSE_PROJECT_NAME=topline-news-prod docker compose -f docker-compose.prod.yml up -d --build
